- hosts: bbb
  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded

  tasks:
    - name: install python dependencies
      package:
        name: python-lxml
        state: present
    - name: download bbb-install script
      get_url:
        url: https://ubuntu.bigbluebutton.org/bbb-install.sh
        dest: ~/bbb-install.sh
# es fehlt der Abschnitt "TURN-Settings anpassen" aus unserer Doku
# hier nun "Anpassungen für Datensparsamkeit"
    - name: disable recordings and logging
      lineinfile:
        path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
        line: '{{item.key}}={{item.value}}'
        regexp: '^(\s+)?{{item.key}}='
      loop:
        - { key: disableRecordingDefault, value: 'true' }
        - { key: breakoutRoomsRecord, value: 'false' }
        - { key: appLogLevel, value: Error }
    - name: logfile retention
      lineinfile:
        path: /etc/cron.daily/bigbluebutton
        line: '{{item.key}}={{item.value}}'
        regexp: '^(\s+)?{{item.key}}='
      loop:
        - { key: history, value: 0 }
        - { key: unrecorded_days, value: 1 }
        - { key: published_days, value: 1 }
        - { key: log_history, value: 1 }
    - name: logging in /usr/share/bbb-web/WEB-INF/classes/logback.xml
      xml:
        path: /usr/share/bbb-web/WEB-INF/classes/logback.xml
        xpath: '{{item}}'
        attribute: level
        value: ERROR
      loop:
        - /configuration/logger
        - /configuration/root

    - name: logging etc/nginx/sites-available/bigbluebutton and etc/nginx/nginx.conf
      lineinfile:
        path: '{{ item }}'
        line: '\1access_log off;'
        regexp: '^((\s+)?)access_log '
        backrefs: yes
      loop:
        - /etc/nginx/nginx.conf
        - /etc/nginx/sites-available/bigbluebutton
      notify: reload nginx
      tags: nginx

# bbb-23
#    - name: disable version in 404 pages /etc/nginx/nginx.conf
#      copy:
#        dest: '/etc/nginx/conf.d/disable-server-version.conf'
#        content: 'server_tokens off;'
#      notify: reload nginx
#      tags: nginx

    - name: reduce logging etc/bbb-*-akka|red5 logback.xml (1)
      xml:
        path: '{{ item[0] }}'
        xpath: '{{ item[1] }}'
        attribute: level
        value: ERROR
      vars:
        files:
# bbb 23
#          - /etc/bbb-transcode-akka/logback.xml
          - /etc/bbb-apps-akka/logback.xml
          - /etc/bbb-fsesl-akka/logback.xml
# bbb 23          - /etc/red5/logback.xml
        xpaths:
          - /configuration/logger
          - /configuration/root
      loop: '{{ files | product(xpaths) | list }}'

    - name: reduce logging etc/bbb-*-akka|red5 logback.xml (2)
      xml:
        path: '{{ item[0] }}'
        xpath: '{{ item[1] }}'
        state: absent
      vars:
        files:
# bbb 23          - /etc/bbb-transcode-akka/logback.xml
          - /etc/bbb-apps-akka/logback.xml
          - /etc/bbb-fsesl-akka/logback.xml
# bbb 23          - /etc/red5/logback.xml
        xpaths:
          - /configuration/logger/level
          - /configuration/root/level
      loop: '{{ files | product(xpaths) | list }}'
    - name: reduce logging */application.conf (1)
      lineinfile:
        path: '{{ item }}'
        line: '\1loglevel = "ERROR"'
        regexp: '^((\s+)?)loglevel = '
        backrefs: yes
      loop:
# bbb 23        - /etc/bbb-transcode-akka/application.conf
        - /etc/bbb-apps-akka/application.conf
        - /etc/bbb-fsesl-akka/application.conf
        - /usr/share/bbb-web/WEB-INF/classes/application.conf
    - name: reduce logging */application.conf (2)
      lineinfile:
        path: '{{ item }}'
        line: '\1stdout-loglevel = "ERROR"'
        regexp: '^((\s+)?)stdout-loglevel = '
        backrefs: yes
      loop:
# bbb 23        - /etc/bbb-transcode-akka/application.conf
        - /etc/bbb-apps-akka/application.conf
        - /etc/bbb-fsesl-akka/application.conf
        - /usr/share/bbb-web/WEB-INF/classes/application.conf
    - name: reduce logging usr/share/bbb-web/WEB-INF/classes/application.conf (1)
      lineinfile:
        path: '{{ item }}'
        line: '\1autoreceive = off'
        regexp: '^((\s+)?)autoreceive = '
        backrefs: yes
      loop:
        - /usr/share/bbb-web/WEB-INF/classes/application.conf
    - name: reduce logging usr/share/bbb-web/WEB-INF/classes/application.conf (2)
      lineinfile:
        path: '{{ item }}'
        line: '\1lifecycle = off'
        regexp: '^((\s+)?)lifecycle = '
        backrefs: yes
      loop:
        - /usr/share/bbb-web/WEB-INF/classes/application.conf
    - name: reduce logging kurento-media-server.service
      lineinfile:
        path: /usr/lib/systemd/system/kurento-media-server.service
        line: 'ExecStart=/usr/bin/kurento-media-server --gst-debug-level=3 --gst-debug="3,Kurento*:3,kms*:3,KurentoWebSocketTransport:3"'
        regexp: '^((\s+)?)ExecStart='
        backrefs: yes
    - name: reduce logging /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml
      lineinfile:
        path: /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml
        line: '  level: warn'
        regexp: '^  level: '
    # BBB 2.3 RC1
    # - name: reduce logging in /opt/freeswitch/conf/autoload_configs/unimrcp.conf.xml
    #   xml:
    #     path: /opt/freeswitch/conf/autoload_configs/unimrcp.conf.xml
    #     xpath: /configuration/settings/param[@name='log-level']
    #     attribute: value
    #     value: WARNING
    #   tags:
    #     - freeswitch
    - name: disable boring sounds
      xml:
        path: /opt/freeswitch/etc/freeswitch/autoload_configs/conference.conf.xml
        xpath: "/configuration/profiles/profile[@name='{{ item[0] }}']/param[@name='{{ item[1] }}']"
        state: absent
        backup: true
      vars:
        profiles: [default, wideband, ultrawideband, cdquality, video-mcu-stereo, sla]
        sounds: [muted-sound, unmuted-sound, alone-sound, moh-sound]
      loop: "{{profiles | product(sounds) | list}}"
      tags: sound

    - name: change welcome message
      ini_file:
        path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
        section: null
        option: '{{ item.option }}'
        value: '{{ item.value }}'
      loop:
        - option: defaultWelcomeMessage
          value: >
            Willkommen!<br><br>Der KalkSpace freut sich, dass du hier bist.
            Bitte beachte, dass auch hier unser
            <a href="https://discuss.kalk.space/t/code-of-conduct/262">Code of Conduct</a> gilt.
            <br><br> Verwende Headset oder Kopfh&ouml;rer, um Hintergrundger&auml;usche zu reduzieren.
        - option: defaultWelcomeMessageFooter
          value: >
            Um an diesem Treffen per Telefon teilzunehmen, w&auml;hle<br>
            <strong>%%DIALNUM%%</strong>.<br> Gib dann <strong>%%CONFNUM%%</strong> als Konferenz-PIN ein.
            Mit der 0 kannst du dich (ent-)muten.
      tags: welcomeMessage

    - name: edit meteor config
      vars:
        config_override:
          public:
            kurento:
              cameraProfiles:
              - id: low
                name: Low quality
                default: true
                bitrate: 80
              - id: medium
                name: Medium quality
                default: false
                bitrate: 200
              - id: high
                name: High quality
                default: false
                bitrate: 500
      block:
        - name: read config file
          slurp:
            path: /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
          register: meteor_config_raw
        - name: extract config of meteor
          set_fact:
            meteor_config: "{{ meteor_config_raw['content'] | b64decode | from_yaml }}"
        - name: update meteor confi
          copy:
            content: '{{ meteor_config | combine(config_override, recursive=true) | to_nice_yaml }}'
            dest: /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
            backup: yes
      tags: meteor

    - name: add webserver content
      copy:
        src: "files/{{item.source}}"
        dest: "/var/www/bigbluebutton-default/{{item.destination}}"
      loop:
        - source: default-presentation.pdf
          destination: default.pdf
        - source: landingpage.html
          destination: index.html
        - source: Anleitung_BBB_Kalkspace.pdf
          destination: Anleitung_BBB_Kalkspace.pdf
      tags: content

    - name: configure dial-in
      copy:
        src: "files/sipgate.xml"
        dest: "/opt/freeswitch/etc/freeswitch/dialplan/public/sipgate.xml"
      tags: dial-in
